name: Python package (full paths to Titanic-Project)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Debug — list files
        run: |
          echo "workspace: $GITHUB_WORKSPACE"
          pwd
          ls -la
          find . -maxdepth 4 -type f | sort

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r Titanic-Project/requirements/requirements.txt
          pip install -r Titanic-Project/requirements/test_requirements.txt

      # Optional: train if this script exists
      - name: Train pipeline
        run: |
          python Titanic-Project/titanic_model/train_pipeline.py

      - name: Run tests
        run: |
          python -m pytest -q Titanic-Project/tests
